version: '3'
services:
  users:
    build:
      context: ./users
      dockerfile: ./cmd/users/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  todo:
    build:
      context: ./todo
      dockerfile: ./cmd/todo/Dockerfile
    ports:
      - "3001:3000"
  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: ibs_test
      POSTGRES_USER: ibs_test
      POSTGRES_PASSWORD: ibs_test
      POSTGRES_PORT: 5432
    ports:
      - "5430:5432"
  migrate:
    build:
      context: ./todo
      dockerfile: ./cmd/migrations/Dockerfile
    depends_on:
      - postgres