version: '3'
services:
  jaeger:
    container_name: jaeger_container
    restart: always
    image: jaegertracing/all-in-one:1.21
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=notifications
      - RABBITMQ_DEFAULT_PASS=notifications
  gateway-service:
    build:
      context: ./gateway
      dockerfile: ./cmd/gateway/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - users-service
  users-service:
    build:
      context: ./users
      dockerfile: ./cmd/users/Dockerfile
    ports:
      - "3001:3000"
      - "50000:50000"
    depends_on:
      - postgres
      - rabbitmq
  todo-service:
    build:
      context: ./todo
      dockerfile: ./cmd/todo/Dockerfile
    ports:
      - "3002:3000"
      - "50000:50000"
    depends_on:
      - postgres
      - rabbitmq
  notifications-service:
    build:
      context: ./notifications
      dockerfile: ./cmd/notifications/Dockerfile
    ports:
      - "465:465"
    depends_on:
      - rabbitmq
  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: ibs_test
      POSTGRES_USER: ibs_test
      POSTGRES_PASSWORD: ibs_test
      POSTGRES_PORT: 5432
    ports:
      - "5431:5432"
  migrate-users:
    build:
      context: ./users
      dockerfile: ./cmd/migrations/Dockerfile
    depends_on:
      - postgres
  migrate-todo:
    build:
      context: ./todo
      dockerfile: ./cmd/migrations/Dockerfile
    depends_on:
      - postgres