version: '3'
services:
  users:
    build:
      context: ./users
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
#  todo:
#    build:
#      context: ./todo
#      dockerfile: ./Dockerfile
#    ports:
#      - "3001:3000"
