version: '3'
services:
  users:
    build:
      context: ./users
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
#  todo:
#    build:
#      context: ./todo
#      dockerfile: ./Dockerfile
#    ports:
#      - "3001:3000"
  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
  migrate:
    build:
      context: ./users
    depends_on:
      - postgres
    volumes:
      - "../migrations:/migrations"
    environment:
      - CGO_ENABLED=1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DBNAME=postgres
    entrypoint: ["/bin/migrations_bin"]