version: '3'
services:
  users:
    build:
      context: ./users
      dockerfile: ./cmd/users/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  #  todo:
#    build:
#      context: ./todo
#      dockerfile: ./Dockerfile
#    ports:
#      - "3001:3000"
  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5431:5432"
  migrate:
    build:
      context: ./users
      dockerfile: ./cmd/migrations/Dockerfile
    depends_on:
      - postgres