### Send POST request with json body
POST {{host}}/login
Content-Type: application/json

{
  "username": "epopov",
  "password": "epopov"
}

### Send POST request with json body
POST {{host}}/login
Content-Type: application/json

{
  "username": "eppopov",
  "password": "eppopov"
}

### Send POST request with json body
POST {{host}}/login
Content-Type: application/json

{
  "username": "epopov",
  "password": "eppopov"
}

