// Code generated by MockGen. DO NOT EDIT.
// Source: gateway/internal/service (interfaces: TodoServiceClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "gateway/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTodoServiceClient is a mock of TodoServiceClient interface.
type MockTodoServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockTodoServiceClientMockRecorder
}

// MockTodoServiceClientMockRecorder is the mock recorder for MockTodoServiceClient.
type MockTodoServiceClientMockRecorder struct {
	mock *MockTodoServiceClient
}

// NewMockTodoServiceClient creates a new mock instance.
func NewMockTodoServiceClient(ctrl *gomock.Controller) *MockTodoServiceClient {
	mock := &MockTodoServiceClient{ctrl: ctrl}
	mock.recorder = &MockTodoServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoServiceClient) EXPECT() *MockTodoServiceClientMockRecorder {
	return m.recorder
}

// CreateToDo mocks base method.
func (m *MockTodoServiceClient) CreateToDo(arg0 context.Context, arg1 *models.CreateTodoDTO) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToDo", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToDo indicates an expected call of CreateToDo.
func (mr *MockTodoServiceClientMockRecorder) CreateToDo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToDo", reflect.TypeOf((*MockTodoServiceClient)(nil).CreateToDo), arg0, arg1)
}

// DeleteToDo mocks base method.
func (m *MockTodoServiceClient) DeleteToDo(arg0 context.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToDo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteToDo indicates an expected call of DeleteToDo.
func (mr *MockTodoServiceClientMockRecorder) DeleteToDo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToDo", reflect.TypeOf((*MockTodoServiceClient)(nil).DeleteToDo), arg0, arg1)
}

// GetToDo mocks base method.
func (m *MockTodoServiceClient) GetToDo(arg0 context.Context, arg1 int) (*models.TodoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToDo", arg0, arg1)
	ret0, _ := ret[0].(*models.TodoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToDo indicates an expected call of GetToDo.
func (mr *MockTodoServiceClientMockRecorder) GetToDo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToDo", reflect.TypeOf((*MockTodoServiceClient)(nil).GetToDo), arg0, arg1)
}

// GetToDos mocks base method.
func (m *MockTodoServiceClient) GetToDos(arg0 context.Context, arg1 int) (*models.TodoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToDos", arg0, arg1)
	ret0, _ := ret[0].(*models.TodoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToDos indicates an expected call of GetToDos.
func (mr *MockTodoServiceClientMockRecorder) GetToDos(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToDos", reflect.TypeOf((*MockTodoServiceClient)(nil).GetToDos), arg0, arg1)
}

// UpdateToDo mocks base method.
func (m *MockTodoServiceClient) UpdateToDo(arg0 context.Context, arg1 *models.UpdateTodoDTO) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateToDo", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateToDo indicates an expected call of UpdateToDo.
func (mr *MockTodoServiceClientMockRecorder) UpdateToDo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateToDo", reflect.TypeOf((*MockTodoServiceClient)(nil).UpdateToDo), arg0, arg1)
}
